name: java_project_deployment
on: workflow_dispatch

jobs:
  source_code_checkout:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout for source code
        uses: actions/checkout@v5
      
  java_setup:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Java
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
         
  build: 
   runs-on: ubuntu-22.04
   steps: 
      - name: Java build
        run: mvn clean install
